services:
  backend:
    image: ghcr.io/Lisi4ka59/emk-backend:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emk_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - emk_network

  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: emk_project
    volumes:
      - postgres_prod_data:/var/lib/postgresql
    networks:
      - emk_network

volumes:
  postgres_prod_data:

networks:
  emk_network: