services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend_blue
      - backend_green
    networks:
      - emk_network

  backend_blue:
    image: ghcr.io/Lisi4ka59/emk-backend:${BACKEND_TAG}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emk_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - emk_network

  backend_green:
    image: ghcr.io/Lisi4ka59/emk-backend:${BACKEND_TAG}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/emk_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - emk_network

  postgres:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql/data/18/main
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - emk_network

volumes:
  postgres_data:

networks:
  emk_network: